#######################################
####  SplatoonPlugin  Config.yml   ####
####      設定の方法と説明         ####
#######################################

#blockSet: true //ワールドに直接書き込む この設定は現在falseにすると凄く重いです。調整中です。
#particle: true //パーティクルを使用する
#ikaChangeEvent: SNEAK //イカ状態変化。 DROP か SNEAK か
#defaultClass: default //デフォルトで装備するクラス名

#######################################
## イカ達の移動速度
 
#moveSpeed: 0.25 //人間状態の移動速度
#ikaSpeed: 0.5 //イカ状態の移動速度
#downSpeed: 0.1 //敵インク上の移動速度
#downSteps: true //自動的に段差を降りる

#######################################
## インクの設定

#inkGauge: 50 //最大インクゲージ
#inkHealSpeed: 1 //インクの回復速度
#inkHeal: 1 //インクの回復量

#######################################
## イカの体力設定

#healDelay: 50 //ダメージを喰らってから回復し始めるまでの待機時間
#healSpeed: 1 //体力の回復速度
#heal: 0.5 //体力の回復量

#######################################
## インクのブロック設定

#inkType: WOOL //羊毛がいやならCLAYにしてください
#inkCanselBlocks: 44:0,1,7,44:3 //インクを受け付けないブロック 指定方法: ID:SubID,ID:SubID

#######################################
## 音の設定

#shootPaintSounds: SLIME_ATTACK/1/2
#usePaintSounds: SLIME_ATTACK/1/2

#######################################
# 以下 初期設定

blockSet: false
particle: true
ikaChangeEvent: SNEAK
defaultClass: default

moveSpeed: 0.2
ikaSpeed: 0.4
downSpeed: 0.1
downSteps: true

inkGauge: 50
inkHealSpeed: 1
inkHeal: 1

healDelay: 50
healSpeed: 1
heal: 0.5

inkType: WOOL
inkCanselBlocks: 6,7,8,9,10,11,26,31,38,50,55,65,66,69,70,75,76,78,106,117,131,140,143,144,44:0

shootPaintSounds: SLIME_ATTACK/1/2
usePaintSounds: SLIME_ATTACK/1/2
